<script setup lang="ts">
import { onMounted, ref, watch } from 'vue'
import { currentLocale, useCampusPulseDomLocalization } from '../i18n/locale.ts'

const pageRoot = ref<HTMLElement | null>(null)
useCampusPulseDomLocalization(pageRoot)

const innovations = [
  { icon: 'fa-database', kicker: '数据基础', title: '真实数据驱动的人群孪生', text: '从脱敏论坛语义中提取行为情境、角色与 Profile，在不还原现实身份的前提下保留人群异质性。', facts: ['17 个宏角色', '120 个微角色', '22,477 个 Profile'] },
  { icon: 'fa-arrows-rotate', kicker: '认知引擎', title: 'SMC 认知状态双向闭环', text: '状态粒子约束 LLM 的表达边界，LLM 已表露的立场又作为观测值反向更新粒子权重，避免让模型直接自报心理数值。', facts: ['10 粒子 / Agent', '12 维认知状态', 'ESS 退化重采样'] },
  { icon: 'fa-layer-group', kicker: '传播结构', title: '六重约束与双层传播网络', text: '身份、利益位置、动态认知、局部观测、行为连续性和结构化动作共同限制 Agent，公开论坛与私聊网络分别承载显性与隐性传播。', facts: ['6 重行为约束', '公共 + 私有渠道', '8 条初始关系 / Agent'] },
  { icon: 'fa-code-branch', kicker: '实验设计', title: '可比较的平行孪生实验', text: '干预前共享历史、随机种子与动作预算，只在指定决策点分叉，使不同治理策略的差异能够被追踪与量化。', facts: ['共享演化前缀', '强制策略分叉', '反事实 + 双重差分'] },
]

const qualityMetrics = [
  { value: '0.0053', label: '讨论帖规模 JS 散度', note: '越接近 0，宏观分布越相似' },
  { value: '95.8%', label: '上下文承接率', note: '基础交互质量评测' },
  { value: '0.0%', label: '虚假事实编造率', note: '在报告评测样本中' },
  { value: '99.3%', label: 'LLM 输出与粒子更新对齐率', note: '语义表达与状态更新一致性' },
]

const researchFocus = [
  { index: 'A', label: '人群建模', question: '如何在不还原真实身份的前提下，保留论坛人群的行为异质性？', answer: '脱敏语义情境 → 角色聚类 → Profile → 合成 Agent' },
  { index: 'B', label: '认知约束', question: '如何让 LLM 的文本表达与动态心理状态长期保持一致？', answer: 'SMC 粒子状态 ↔ LLM 表达的双向闭环' },
  { index: 'C', label: '政策评估', question: '如何把治理策略的差异与随机演化的差异分离开？', answer: '共享历史前缀 → 决策点强制分叉 → 反事实对照' },
]

const updateTitle = () => {
  document.title = currentLocale.value === 'en-US'
    ? 'Innovation & evaluation · CampusPulse'
    : '创新与评测 · CampusPulse'
}
onMounted(updateTitle)
watch(currentLocale, updateTitle)
</script>

<template>
  <main ref="pageRoot" class="innovation-page">
    <nav class="breadcrumb" aria-label="面包屑">
      <RouterLink to="/campus-pulse/system">系统与数据</RouterLink><i class="fa-solid fa-chevron-right" aria-hidden="true" /><span>创新与评测</span>
    </nav>

    <header class="innovation-hero">
      <div>
        <span class="eyebrow">INNOVATION · EVALUATION</span>
        <h1>把社会模拟从“能运行”<br><em>推进到“可检查”。</em></h1>
        <p>CampusPulse 将真实数字足迹映射为异质性 Agent，用认知粒子限制大模型表达，并通过共享历史前缀的平行推演比较治理策略。</p>
        <div class="hero-tags" aria-label="Platform principles"><span>TRACEABLE</span><span>COUNTERFACTUAL</span><span>AUDITABLE</span></div>
      </div>
      <aside class="hero-proof" aria-label="系统规模">
        <div><strong>1,000</strong><span>异质性 Agent</span></div>
        <div><strong>10,000</strong><span>总状态粒子</span></div>
        <div><strong>2</strong><span>类实证场景</span></div>
      </aside>
    </header>

    <section class="research-focus" aria-labelledby="research-focus-title">
      <header>
        <span class="focus-marker">RESEARCH<br>FOCUS</span>
        <div><span class="eyebrow">研究主线</span><h2 id="research-focus-title">我们集中回答三个问题</h2></div>
      </header>
      <div class="focus-grid">
        <article v-for="focus in researchFocus" :key="focus.index">
          <span>{{ focus.index }}</span><small>{{ focus.label }}</small>
          <h3>{{ focus.question }}</h3><p>{{ focus.answer }}</p>
        </article>
      </div>
    </section>

    <section class="chapter" aria-labelledby="innovation-title">
      <header class="chapter-heading">
        <div><span class="chapter-number">01</span><h2 id="innovation-title">四项核心创新</h2></div>
        <p>从人群建模、个体状态到信息传播和对照实验，把模型生成纳入可追踪的系统约束。</p>
      </header>
      <div class="twin-pipeline" aria-label="从真实数字足迹到合成人群的映射管线">
        <header><span class="eyebrow">DATA → DIGITAL TWIN</span><div><h3>真实数字足迹如何成为合成人群</h3><p>不是人工编写少量角色标签，而是从大规模脱敏语义中逐层提炼行为结构。</p></div></header>
        <ol>
          <li><strong>586,970</strong><span>原始帖子与评论</span><small>4 YEARS</small></li>
          <li><strong>582,408</strong><span>去重语义行</span><small>DEDUPLICATED</small></li>
          <li><strong>131,604</strong><span>行为情境</span><small>CONTEXTS</small></li>
          <li><strong>22,477</strong><span>Profile 集合</span><small>PROFILES</small></li>
          <li class="pipeline-result"><strong>1,000</strong><span>异质性 Agent</span><small>DIGITAL TWIN</small></li>
        </ol>
      </div>
      <div class="innovation-grid">
        <article v-for="item in innovations" :key="item.title" class="innovation-card">
          <header><span class="card-kicker">{{ item.kicker }}</span><i class="fa-solid" :class="item.icon" aria-hidden="true" /></header>
          <h3>{{ item.title }}</h3><p>{{ item.text }}</p>
          <ul><li v-for="fact in item.facts" :key="fact">{{ fact }}</li></ul>
        </article>
      </div>
    </section>

    <section class="loop-panel" aria-labelledby="loop-title">
      <div class="loop-copy"><span class="eyebrow">CORE MECHANISM</span><h2 id="loop-title">粒子与 LLM 的双向认知闭环</h2><p>系统先将粒子期望写入生成上下文，再把 Agent 的实际表达作为观测，通过贝叶斯似然更新权重。</p></div>
      <div class="loop-diagram" aria-label="SMC 双向闭环流程">
        <div><small>STATE</small><strong>10 个粒子</strong><span>12 维隐状态</span></div>
        <i class="fa-solid fa-arrow-right-long" aria-hidden="true" />
        <div class="loop-core"><small>GENERATION</small><strong>LLM 表达</strong><span>文本、行为与立场</span></div>
        <i class="fa-solid fa-arrow-right-long" aria-hidden="true" />
        <div><small>UPDATE</small><strong>权重更新</strong><span>ESS 监测与重采样</span></div>
      </div>
      <p class="loop-return"><i class="fa-solid fa-arrow-rotate-left" aria-hidden="true" /> 新状态返回下一个 Tick，继续限制 Agent 的语义边界</p>
    </section>

    <section class="chapter" aria-labelledby="quality-title">
      <header class="chapter-heading"><div><span class="chapter-number">02</span><h2 id="quality-title">模拟真实性与一致性</h2></div><p>评测数字来自报告中的真实论坛对齐、微观一致性和约束消融实验。</p></header>
      <div class="metric-grid"><article v-for="metric in qualityMetrics" :key="metric.label"><strong>{{ metric.value }}</strong><h3>{{ metric.label }}</h3><p>{{ metric.note }}</p></article></div>
      <div class="validation-map" aria-label="从宏观生态到治理效能的四层验证框架">
        <header><span class="eyebrow">VALIDATION FRAMEWORK</span><h3>不只看“像不像”，而是逐层检验</h3></header>
        <ol>
          <li><span>01</span><div><strong>宏观生态</strong><small>回复规模分布与真实论坛对齐</small></div><b>JS 0.0053</b></li>
          <li><span>02</span><div><strong>微观一致性</strong><small>上下文、语言风格与状态对齐</small></div><b>99.3%</b></li>
          <li><span>03</span><div><strong>群体异质性</strong><small>利益位置能解释演化后的群体差异</small></div><b>p = 0.005</b></li>
          <li><span>04</span><div><strong>治理动作效能</strong><small>用平行分支和双重差分检查政策响应</small></div><b>DID</b></li>
        </ol>
      </div>
      <div class="ablation-panel">
        <div><span class="eyebrow">ABLATION STUDY</span><h3>完整输入确实改变了 Agent 行为</h3><p>固定外部环境，对比纯上下文、Profile 约束、状态约束与完整输入。</p></div>
        <dl><div><dt>75%</dt><dd>改变主动作</dd></div><div><dt>91.7%</dt><dd>改变情绪表现</dd></div><div><dt>66.7%</dt><dd>改变私聊触发</dd></div><div><dt>70.8%</dt><dd>约束条件识别率</dd></div></dl>
      </div>
    </section>

    <section class="chapter" aria-labelledby="comparison-title">
      <header class="chapter-heading"><div><span class="chapter-number">03</span><h2 id="comparison-title">平行策略对比</h2></div><p>同一事件共享干预前历史，在决策点分为 Natural 与综合干预 D，避免把不同起点误认为政策差异。</p></header>
      <div class="timeline" aria-label="平行孪生分叉时间线"><span>共享初始状态</span><i /><span>事件投入</span><i /><span>锁定共同前缀</span><b>策略分叉</b><div><em>NATURAL</em><em>D · 综合干预</em></div></div>
      <div class="case-grid">
        <article><span>CASE 01 · 突发冲突</span><h3>干预使议题集中，但发言量未减少</h3><dl><div><dt>167 → 173</dt><dd>发言总量</dd></div><div><dt>22 → 4</dt><dd>争论主张</dd></div><div><dt>0.392 → 0.424</dt><dd>群体信任度</dd></div></dl><p>官方渠道将分散的负面表达聚合为对责任与时限的直接质询。</p></article>
        <article><span>CASE 02 · 资源争议</span><h3>服务闭环有效，不等于信任已恢复</h3><dl><div><dt>73 → 76</dt><dd>发言总量</dd></div><div><dt>17 → 10</dt><dd>争论主张</dd></div><div class="negative"><dt>0.429 → 0.375</dt><dd>群体信任度</dd></div></dl><p>工单将服务积压降至零，但在实质资源不足时，程序公开也可能引发新的质询。</p></article>
      </div>
      <div class="governance-chart" aria-labelledby="governance-chart-title">
        <header><span class="eyebrow">COUNTERFACTUAL SIGNAL</span><div><h3 id="governance-chart-title">干预后的信任轨迹</h3><p>从同一决策基线出发，两次治理介入都促成议题收敛，却将群体信任推向不同方向。</p></div></header>
        <div class="trajectory-layout">
          <div class="trajectory-plot" role="img" aria-label="两个治理案例从共同决策点走向相反信任结果的动态轨迹">
            <svg viewBox="0 0 620 330" aria-hidden="true">
              <defs><linearGradient id="trajectoryUp" x1="0" x2="1"><stop stop-color="#37d4e9"/><stop offset="1" stop-color="#087b99"/></linearGradient><linearGradient id="trajectoryDown" x1="0" x2="1"><stop stop-color="#55bdd2"/><stop offset="1" stop-color="#315a7c"/></linearGradient></defs>
              <path class="trajectory-grid" d="M70 55H585M70 165H585M70 275H585M180 30V300M310 30V300M440 30V300M570 30V300"/>
              <path class="trajectory-base" d="M45 165H178"/><circle class="origin-node" cx="178" cy="165" r="7"/>
              <path class="trajectory-ghost" d="M178 165C270 165 330 83 515 76"/><path class="trajectory-branch branch--conflict" d="M178 165C270 165 330 83 515 76"/>
              <path class="trajectory-ghost" d="M178 165C267 165 325 231 474 242"/><path class="trajectory-branch branch--resource" d="M178 165C267 165 325 231 474 242"/>
              <circle class="endpoint-halo halo--conflict" cx="515" cy="76" r="21"/><circle class="endpoint endpoint--conflict" cx="515" cy="76" r="8"/>
              <circle class="endpoint-halo halo--resource" cx="474" cy="242" r="18"/><circle class="endpoint endpoint--resource" cx="474" cy="242" r="8"/>
            </svg>
            <span class="plot-axis plot-axis--positive">信任提升</span><span class="plot-axis plot-axis--negative">信任受损</span>
            <span class="plot-origin">共同决策点</span>
            <span class="plot-result plot-result--conflict"><b>CASE 01</b><strong>+0.032</strong></span>
            <span class="plot-result plot-result--resource"><b>CASE 02</b><strong>−0.054</strong></span>
          </div>
          <div class="trajectory-cards">
            <article class="trajectory-card trajectory-card--conflict"><header><span>CASE 01</span><strong>突发冲突</strong><em>信任提升</em></header><dl><div><dt>−81.8%</dt><dd>争论主张</dd></div><div><dt>+6</dt><dd>发言变化</dd></div><div><dt>+0.032</dt><dd>信任变化</dd></div></dl><p>议题显著收敛，讨论仍保持活跃，信任同步回升。</p></article>
            <article class="trajectory-card trajectory-card--resource"><header><span>CASE 02</span><strong>资源争议</strong><em>信任受损</em></header><dl><div><dt>−41.2%</dt><dd>争论主张</dd></div><div><dt>+3</dt><dd>发言变化</dd></div><div><dt>−0.054</dt><dd>信任变化</dd></div></dl><p>服务闭环并未抵消资源不足带来的程序性质询。</p></article>
          </div>
        </div>
        <footer><strong>关键发现</strong><span>治理可以让议题收敛，却不必然降低讨论量，也不自动修复信任。</span></footer>
      </div>
      <blockquote class="research-finding">
        <span>KEY FINDING · 核心发现</span>
        <p>“服务承接有效”，不等于“程序正当性与群体信任已建立”。</p>
        <small>综合干预将资源争议的服务积压降至 0，但群体信任度从 Natural 的 0.429 下降至 0.375。</small>
      </blockquote>
      <RouterLink class="case-link" to="/campus-pulse/results">进入案例中心查看完整分支证据 <i class="fa-solid fa-arrow-right" aria-hidden="true" /></RouterLink>
    </section>

    <section class="chapter boundary-chapter" aria-labelledby="boundary-title">
      <header class="chapter-heading"><div><span class="chapter-number">04</span><h2 id="boundary-title">证据口径与适用边界</h2></div><p>评测结果用于说明特定设定下的模型表现，不是真实全校人群的统计替代。</p></header>
      <div class="boundary-panel">
        <ul><li>合成 Agent 表达社会动力属性，不对应现实学生或现实人际关系。</li><li>极端热点长尾仍有差距：模拟/真实 P99 回复数为 11/33，最大回复数为 15/590。</li><li>报告中“有回复帖子占比差”与“群体信息差”存在不同表格口径，未经证据版本核对前不做跨表直接比较。</li><li>所有结论受初始条件、数据覆盖、随机种子、策略定义与发布门禁约束。</li></ul>
        <div><RouterLink to="/campus-pulse/system?tab=evidence">查看证据目录</RouterLink><RouterLink to="/campus-pulse/system?tab=disclosure">查看架构与数据边界</RouterLink></div>
      </div>
    </section>
  </main>
</template>

<style scoped>
.innovation-page{display:grid;width:min(100%,var(--cp-content-max));gap:var(--cp-space-7);margin:0 auto;padding:var(--cp-space-4) var(--cp-content-gutter) var(--cp-space-8);color:var(--cp-text-primary)}
.breadcrumb{display:flex;align-items:center;gap:var(--cp-space-2);color:var(--cp-text-muted);font-size:var(--cp-text-sm)}.breadcrumb a{color:var(--cp-tech);font-weight:700;text-decoration:none}.breadcrumb i{font-size:.6rem}
.innovation-hero{position:relative;isolation:isolate;display:grid;min-height:24rem;grid-template-columns:minmax(0,1.4fr) minmax(19rem,.6fr);align-items:end;gap:var(--cp-space-8);overflow:hidden;padding:clamp(1.8rem,4vw,3.5rem);border:1px solid var(--cp-hero-border);border-radius:var(--cp-radius-lg);background:radial-gradient(circle at 84% 12%,rgba(13,145,181,.2),transparent 23rem),linear-gradient(135deg,#181616,#171f22 62%,#101415);box-shadow:var(--cp-shadow-floating);color:white}.innovation-hero:before{position:absolute;inset:0;z-index:-1;background-image:linear-gradient(rgba(255,255,255,.025) 1px,transparent 1px),linear-gradient(90deg,rgba(255,255,255,.025) 1px,transparent 1px);background-size:34px 34px;content:'';mask-image:linear-gradient(90deg,black,transparent)}
.eyebrow{display:block;color:#70d5ec;font:800 var(--cp-text-xs)/1 var(--cp-font-mono);letter-spacing:.13em}.innovation-hero h1{margin:var(--cp-space-4) 0 0;font-size:clamp(2.2rem,4vw,4.35rem);font-weight:680;letter-spacing:-.055em;line-height:1.06}.innovation-hero h1 em{color:#d5eef4;font-style:normal}.innovation-hero p{max-width:50rem;margin:var(--cp-space-5) 0 0;color:#c6cfd1;font-size:var(--cp-text-md);line-height:1.8}
.hero-proof{display:grid;gap:1px;overflow:hidden;border:1px solid rgba(255,255,255,.14);border-radius:var(--cp-radius-md);background:rgba(255,255,255,.14)}.hero-proof div{display:grid;grid-template-columns:6.5rem 1fr;align-items:baseline;gap:var(--cp-space-3);padding:var(--cp-space-4);background:rgba(12,16,17,.78)}.hero-proof strong{font:800 var(--cp-text-2xl)/1 var(--cp-font-mono)}.hero-proof span{color:#abb8bb;font-size:var(--cp-text-sm)}
.research-focus{position:relative;display:grid;grid-template-columns:12rem minmax(0,1fr);gap:var(--cp-space-5);overflow:hidden;padding:var(--cp-space-6);border:1px solid var(--cp-tech-line);border-radius:var(--cp-radius-lg);background:linear-gradient(120deg,#e7f7fb 0%,#fafdfe 48%,#fff 100%);box-shadow:var(--cp-tech-glow)}.research-focus:after{position:absolute;right:-5rem;top:-8rem;width:20rem;height:20rem;border:1px solid rgba(13,145,181,.12);border-radius:50%;box-shadow:0 0 0 3rem rgba(13,145,181,.035),0 0 0 6rem rgba(13,145,181,.02);content:'';pointer-events:none}.research-focus>header{position:relative;z-index:1;display:grid;align-content:space-between;border-right:1px solid var(--cp-tech-line);padding-right:var(--cp-space-5)}.focus-marker{color:rgba(11,107,136,.18);font:900 2rem/.9 var(--cp-font-mono);letter-spacing:-.08em}.research-focus h2{margin:var(--cp-space-2) 0 0;font-size:var(--cp-text-xl);line-height:1.2}.focus-grid{position:relative;z-index:1;display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:var(--cp-space-3)}.focus-grid article{display:grid;grid-template-columns:auto 1fr;align-content:start;gap:var(--cp-space-2) var(--cp-space-3);padding:var(--cp-space-4);border:1px solid rgba(185,223,232,.8);border-radius:var(--cp-radius-md);background:rgba(255,255,255,.72)}.focus-grid article>span{grid-row:1/3;color:var(--cp-tech);font:900 2.6rem/.9 var(--cp-font-mono)}.focus-grid article>small{color:var(--cp-tech);font-size:var(--cp-text-xs);font-weight:800;letter-spacing:.08em}.focus-grid h3{grid-column:1/-1;margin:var(--cp-space-2) 0 0;font-size:var(--cp-text-md);line-height:1.55}.focus-grid p{grid-column:1/-1;margin:auto 0 0;padding-top:var(--cp-space-3);border-top:1px solid var(--cp-tech-line);color:var(--cp-tech);font-size:var(--cp-text-xs);font-weight:700}
.chapter{display:grid;gap:var(--cp-space-5)}.chapter-heading{display:flex;align-items:end;justify-content:space-between;gap:var(--cp-space-6);padding-bottom:var(--cp-space-4);border-bottom:1px solid var(--cp-border-default)}.chapter-heading>div{display:flex;align-items:center;gap:var(--cp-space-3)}.chapter-number{color:var(--cp-tech);font:800 var(--cp-text-sm)/1 var(--cp-font-mono)}.chapter-heading h2,.boundary-panel h2{margin:0;font-size:var(--cp-text-2xl);letter-spacing:-.03em}.chapter-heading p{max-width:42rem;margin:0;color:var(--cp-text-secondary);font-size:var(--cp-text-sm);text-align:right}
.chapter-number{display:inline-grid;min-width:3.6rem;place-items:center;color:var(--cp-tech);font:900 2.7rem/.85 var(--cp-font-mono);letter-spacing:-.09em}.chapter-heading h2,.boundary-panel h2{margin:0;font-size:clamp(1.8rem,2.5vw,2.7rem);letter-spacing:-.04em}.chapter-heading p{max-width:42rem;margin:0;color:var(--cp-text-secondary);font-size:var(--cp-text-sm);text-align:right}
.innovation-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:var(--cp-space-4)}.innovation-card{position:relative;display:grid;min-height:20rem;gap:var(--cp-space-3);overflow:hidden;padding:var(--cp-space-6);border:1px solid var(--cp-border-default);border-radius:var(--cp-radius-lg);background:linear-gradient(145deg,var(--cp-surface-default),#fbfdfe);box-shadow:var(--cp-shadow-card);transition:transform var(--cp-motion-standard) ease,box-shadow var(--cp-motion-standard) ease,border-color var(--cp-motion-standard) ease}.innovation-card:after{position:absolute;right:-2rem;bottom:-3rem;color:rgba(11,107,136,.035);content:attr(data-index);font:900 10rem/1 var(--cp-font-mono)}.innovation-card:hover{border-color:var(--cp-tech-line);box-shadow:var(--cp-shadow-card-hover);transform:translateY(-3px)}.innovation-card header{display:flex;align-items:flex-start;justify-content:space-between;color:var(--cp-tech)}.card-index{font:900 3.15rem/.8 var(--cp-font-mono);letter-spacing:-.1em}.innovation-card header i{display:grid;width:3.35rem;height:3.35rem;place-items:center;border:1px solid var(--cp-tech-line);border-radius:50%;background:var(--cp-tech-surface);font-size:var(--cp-text-lg);box-shadow:0 8px 24px rgba(11,107,136,.12)}.innovation-card h3{position:relative;z-index:1;margin:var(--cp-space-2) 0 0;font-size:clamp(1.2rem,1.7vw,1.55rem);letter-spacing:-.02em}.innovation-card p{position:relative;z-index:1;margin:0;color:var(--cp-text-secondary);font-size:var(--cp-text-md);line-height:1.8}.innovation-card ul{position:relative;z-index:1;display:flex;flex-wrap:wrap;align-self:end;gap:var(--cp-space-2);margin:0;padding:0;list-style:none}.innovation-card li{padding:.42rem .72rem;border:1px solid var(--cp-tech-line);border-radius:99px;background:var(--cp-tech-surface);color:var(--cp-tech);font-size:var(--cp-text-xs);font-weight:750}
.loop-panel{display:grid;grid-template-columns:minmax(18rem,.7fr) minmax(28rem,1.3fr);gap:var(--cp-space-6);padding:var(--cp-space-6);border:1px solid var(--cp-tech-line);border-radius:var(--cp-radius-lg);background:linear-gradient(125deg,#eefafd,var(--cp-surface-default));box-shadow:var(--cp-tech-glow)}.loop-copy h2{margin:var(--cp-space-3) 0;font-size:var(--cp-text-xl)}.loop-copy p{margin:0;color:var(--cp-text-secondary);font-size:var(--cp-text-sm);line-height:1.75}.loop-diagram{display:grid;grid-template-columns:1fr auto 1fr auto 1fr;align-items:center;gap:var(--cp-space-3)}.loop-diagram>div{display:grid;min-height:8rem;align-content:center;gap:var(--cp-space-2);padding:var(--cp-space-4);border:1px solid var(--cp-border-default);border-radius:var(--cp-radius-md);background:white;text-align:center}.loop-diagram .loop-core{border-color:var(--cp-action-primary);background:var(--cp-surface-selected)}.loop-diagram small{color:var(--cp-tech);font:800 .68rem/1 var(--cp-font-mono)}.loop-diagram span{color:var(--cp-text-muted);font-size:var(--cp-text-xs)}.loop-diagram>i{color:var(--cp-tech)}.loop-return{grid-column:2;margin:0;color:var(--cp-evidence-text);font-size:var(--cp-text-xs);text-align:center}
.metric-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:var(--cp-space-3)}.metric-grid article{padding:var(--cp-space-5);border-top:3px solid var(--cp-tech);background:var(--cp-surface-default);box-shadow:var(--cp-shadow-card)}.metric-grid strong{color:var(--cp-tech);font:800 clamp(1.8rem,3vw,2.8rem)/1 var(--cp-font-mono)}.metric-grid h3{margin:var(--cp-space-3) 0 var(--cp-space-1);font-size:var(--cp-text-sm)}.metric-grid p{margin:0;color:var(--cp-text-muted);font-size:var(--cp-text-xs)}
.validation-map{display:grid;grid-template-columns:minmax(14rem,.42fr) minmax(30rem,1.58fr);gap:var(--cp-space-5);padding:var(--cp-space-5);border:1px solid var(--cp-border-default);border-radius:var(--cp-radius-lg);background:linear-gradient(135deg,#17191a,#12232a);box-shadow:var(--cp-shadow-floating);color:white}.validation-map header{align-self:center}.validation-map h3{margin:var(--cp-space-3) 0 0;font-size:var(--cp-text-xl);line-height:1.35}.validation-map ol{display:grid;gap:1px;margin:0;padding:0;border:1px solid rgba(255,255,255,.12);border-radius:var(--cp-radius-md);background:rgba(255,255,255,.12);list-style:none}.validation-map li{display:grid;grid-template-columns:2.7rem 1fr auto;align-items:center;gap:var(--cp-space-3);padding:var(--cp-space-3) var(--cp-space-4);background:rgba(12,17,19,.88)}.validation-map li>span{color:#70d5ec;font:850 var(--cp-text-sm)/1 var(--cp-font-mono)}.validation-map li>div{display:grid;gap:2px}.validation-map li strong{font-size:var(--cp-text-sm)}.validation-map li small{color:#9facaf;font-size:var(--cp-text-xs)}.validation-map li b{min-width:6.4rem;color:#b8edf7;font:850 var(--cp-text-md)/1 var(--cp-font-mono);text-align:right}
.ablation-panel{display:grid;grid-template-columns:minmax(17rem,.65fr) minmax(30rem,1.35fr);gap:var(--cp-space-6);padding:var(--cp-space-5);border:1px solid var(--cp-border-default);border-radius:var(--cp-radius-md);background:var(--cp-surface-default)}.ablation-panel h3{margin:var(--cp-space-3) 0 var(--cp-space-2)}.ablation-panel p{margin:0;color:var(--cp-text-secondary);font-size:var(--cp-text-sm)}.ablation-panel dl{display:grid;grid-template-columns:repeat(4,1fr);margin:0}.ablation-panel dl div{display:grid;align-content:center;gap:var(--cp-space-2);border-left:1px solid var(--cp-border-default);padding:var(--cp-space-3);text-align:center}.ablation-panel dt{color:var(--cp-action-primary);font:800 var(--cp-text-xl)/1 var(--cp-font-mono)}.ablation-panel dd{margin:0;color:var(--cp-text-secondary);font-size:var(--cp-text-xs)}
.timeline{display:grid;grid-template-columns:auto 1fr auto 1fr auto;align-items:center;gap:var(--cp-space-3);padding:var(--cp-space-5);border:1px solid var(--cp-border-default);border-radius:var(--cp-radius-md);background:var(--cp-surface-default);font-size:var(--cp-text-sm);font-weight:700}.timeline>i{height:1px;background:var(--cp-border-strong)}.timeline>b{grid-column:1/-1;justify-self:center;padding:.25rem .65rem;border-radius:99px;background:var(--cp-action-primary);color:white;font-size:var(--cp-text-xs)}.timeline>div{display:grid;grid-column:1/-1;grid-template-columns:1fr 1fr;gap:var(--cp-space-3);width:100%}.timeline em{padding:var(--cp-space-3);border:1px solid var(--cp-border-default);border-radius:var(--cp-radius-sm);background:var(--cp-surface-subtle);font-style:normal;text-align:center}.timeline em:last-child{border-color:#e3aab5;background:var(--cp-surface-selected);color:var(--cp-action-primary)}
.case-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:var(--cp-space-4)}.case-grid article{display:grid;gap:var(--cp-space-3);padding:var(--cp-space-5);border:1px solid var(--cp-border-default);border-radius:var(--cp-radius-md);background:var(--cp-surface-default);box-shadow:var(--cp-shadow-card)}.case-grid article>span{color:var(--cp-tech);font:800 var(--cp-text-xs)/1 var(--cp-font-mono)}.case-grid h3{margin:0;font-size:var(--cp-text-lg)}.case-grid dl{display:grid;grid-template-columns:repeat(3,1fr);margin:0;border-block:1px solid var(--cp-border-default)}.case-grid dl div{padding:var(--cp-space-3);border-left:1px solid var(--cp-border-default)}.case-grid dl div:first-child{border-left:0}.case-grid dt{font:800 var(--cp-text-md)/1.2 var(--cp-font-mono)}.case-grid dd{margin:var(--cp-space-1) 0 0;color:var(--cp-text-muted);font-size:var(--cp-text-xs)}.case-grid .negative dt{color:var(--cp-danger)}.case-grid p{margin:0;color:var(--cp-text-secondary);font-size:var(--cp-text-sm);line-height:1.7}.case-link{justify-self:end;color:var(--cp-tech);font-size:var(--cp-text-sm);font-weight:750;text-decoration:none}
.research-finding{position:relative;display:grid;gap:var(--cp-space-3);overflow:hidden;margin:0;padding:var(--cp-space-6) clamp(1.5rem,4vw,3rem);border:0;border-left:6px solid var(--cp-action-primary);border-radius:0 var(--cp-radius-lg) var(--cp-radius-lg) 0;background:linear-gradient(110deg,#211517,#15191b);box-shadow:var(--cp-shadow-floating);color:white}.research-finding:after{position:absolute;right:2rem;top:-2.5rem;color:rgba(255,255,255,.045);content:'“';font:900 14rem/1 Georgia,serif}.research-finding span{position:relative;z-index:1;color:#e8a8b6;font:800 var(--cp-text-xs)/1 var(--cp-font-mono);letter-spacing:.12em}.research-finding p{position:relative;z-index:1;max-width:65rem;margin:0;font-size:clamp(1.4rem,2.4vw,2.25rem);font-weight:720;letter-spacing:-.03em;line-height:1.4}.research-finding small{position:relative;z-index:1;color:#bdb5b6;font-size:var(--cp-text-sm)}
.boundary-panel{display:grid;gap:var(--cp-space-5);padding:var(--cp-space-6);border:1px solid #e6cf96;border-radius:var(--cp-radius-lg);background:var(--cp-evidence-surface)}.boundary-panel header{display:flex;align-items:baseline;gap:var(--cp-space-3)}.boundary-panel .chapter-number{min-width:auto;font-size:var(--cp-text-lg);letter-spacing:-.03em;white-space:nowrap}.boundary-panel header p{margin:var(--cp-space-2) 0 0;color:var(--cp-evidence-text);font-size:var(--cp-text-sm)}.boundary-panel ul{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:var(--cp-space-3) var(--cp-space-6);margin:0;padding-left:1.2rem;color:var(--cp-evidence-text);font-size:var(--cp-text-sm);line-height:1.7}.boundary-panel>div{display:flex;flex-wrap:wrap;gap:var(--cp-space-2)}.boundary-panel a{display:inline-flex;min-height:var(--cp-control-height);align-items:center;padding:0 var(--cp-space-3);border:1px solid #bba767;border-radius:var(--cp-radius-sm);background:white;color:var(--cp-evidence-text);font-size:var(--cp-text-sm);font-weight:700;text-decoration:none}

/* Visual narrative: luminous instrumentation, restrained depth, and clearer chapter rhythm. */
.innovation-page{position:relative;isolation:isolate;gap:clamp(2.5rem,5vw,5rem)}
.innovation-page:before{position:fixed;inset:7rem 0 0 17rem;z-index:-1;background:radial-gradient(circle at 72% 8%,rgba(20,160,199,.07),transparent 27rem),radial-gradient(circle at 28% 48%,rgba(176,18,55,.045),transparent 32rem);content:'';pointer-events:none}
.breadcrumb{width:max-content;padding:.42rem .7rem;border:1px solid rgba(11,107,136,.12);border-radius:999px;background:rgba(255,255,255,.72);backdrop-filter:blur(12px)}
.innovation-hero{min-height:31rem;grid-template-columns:minmax(0,1.55fr) minmax(18rem,.45fr);align-items:center;border-color:rgba(112,213,236,.26);background:radial-gradient(circle at 75% 18%,rgba(26,189,224,.2),transparent 19rem),radial-gradient(circle at 8% 110%,rgba(176,18,55,.18),transparent 27rem),linear-gradient(130deg,#0d1114,#111d22 58%,#071317);box-shadow:0 28px 70px rgba(12,24,29,.18),inset 0 1px rgba(255,255,255,.08)}
.innovation-hero:before{background-image:linear-gradient(rgba(112,213,236,.045) 1px,transparent 1px),linear-gradient(90deg,rgba(112,213,236,.045) 1px,transparent 1px);background-size:32px 32px;mask-image:linear-gradient(90deg,black 15%,rgba(0,0,0,.35) 72%,transparent)}
.innovation-hero:after{position:absolute;right:clamp(15rem,25vw,25rem);top:-8rem;width:25rem;height:25rem;border:1px solid rgba(112,213,236,.16);border-radius:50%;box-shadow:0 0 0 3.6rem rgba(112,213,236,.025),0 0 0 7.2rem rgba(112,213,236,.018);content:'';pointer-events:none}
.innovation-hero>div,.hero-proof{position:relative;z-index:1}.innovation-hero .eyebrow:before{display:inline-block;width:2rem;height:1px;margin-right:.65rem;background:#70d5ec;content:'';vertical-align:middle}.innovation-hero h1{max-width:52rem;font-size:clamp(3rem,4.8vw,5.15rem);line-height:.98;text-wrap:balance}.innovation-hero h1 em{background:linear-gradient(90deg,#eafcff,#79dcef);background-clip:text;color:transparent}.innovation-hero p{max-width:48rem;color:#b8c7cb;font-size:clamp(.95rem,1.25vw,1.1rem)}
.hero-tags{display:flex;flex-wrap:wrap;gap:.55rem;margin-top:var(--cp-space-5)}.hero-tags span{padding:.45rem .7rem;border:1px solid rgba(112,213,236,.22);border-radius:999px;background:rgba(112,213,236,.06);color:#9ee9f7;font:750 .68rem/1 var(--cp-font-mono);letter-spacing:.1em}
.hero-proof{border-color:rgba(112,213,236,.24);border-radius:1rem;background:rgba(112,213,236,.14);box-shadow:0 20px 45px rgba(0,0,0,.22);backdrop-filter:blur(18px)}.hero-proof div{position:relative;min-height:6rem;align-items:center;background:rgba(7,16,20,.8)}.hero-proof div:after{position:absolute;right:1rem;bottom:.65rem;width:2.8rem;height:2px;background:linear-gradient(90deg,transparent,#70d5ec);content:''}.hero-proof strong{color:#f7fdff;text-shadow:0 0 22px rgba(112,213,236,.18)}.hero-proof span{line-height:1.35}
.research-focus{grid-template-columns:10rem minmax(0,1fr);border-color:rgba(20,154,191,.22);background:linear-gradient(118deg,rgba(224,248,253,.92),rgba(255,255,255,.95) 55%);box-shadow:0 18px 45px rgba(11,107,136,.08)}.focus-marker{color:rgba(11,107,136,.24)}.focus-grid article{position:relative;overflow:hidden;border-color:rgba(53,166,195,.18);background:rgba(255,255,255,.78);box-shadow:0 10px 24px rgba(35,100,119,.055);transition:transform var(--cp-motion-standard) ease,border-color var(--cp-motion-standard) ease}.focus-grid article:hover{border-color:rgba(13,145,181,.45);transform:translateY(-3px)}.focus-grid article:after{position:absolute;right:-2rem;bottom:-2rem;width:6rem;height:6rem;border:1px solid rgba(13,145,181,.1);border-radius:50%;content:''}
.chapter-heading{position:relative;padding:0 0 var(--cp-space-4) 1rem;border-bottom-color:rgba(11,107,136,.18)}.chapter-heading:before{position:absolute;left:0;top:0;width:3px;height:100%;border-radius:3px;background:linear-gradient(var(--cp-tech),transparent);content:''}.chapter-number{background:linear-gradient(180deg,#0d8eaf,#075c74);background-clip:text;color:transparent;text-shadow:0 8px 24px rgba(11,107,136,.18)}
.innovation-card{min-height:21rem;border-color:rgba(11,107,136,.14);background:linear-gradient(145deg,rgba(255,255,255,.98),rgba(240,250,252,.75));box-shadow:0 16px 38px rgba(31,70,82,.075)}.innovation-card:before{position:absolute;inset:0 0 auto;height:3px;background:linear-gradient(90deg,var(--cp-tech),#75dcef 42%,transparent 82%);content:''}.innovation-card:hover{border-color:rgba(13,145,181,.38);box-shadow:0 24px 48px rgba(22,93,113,.13);transform:translateY(-5px)}.innovation-card header i{border-color:rgba(13,145,181,.22);background:linear-gradient(145deg,#e9fafd,#fff);box-shadow:0 0 0 7px rgba(13,145,181,.045),0 12px 25px rgba(11,107,136,.12)}
.twin-pipeline{position:relative;display:grid;gap:var(--cp-space-5);overflow:hidden;padding:var(--cp-space-5);border:1px solid rgba(112,213,236,.2);border-radius:var(--cp-radius-lg);background:radial-gradient(circle at 90% -20%,rgba(77,209,236,.17),transparent 20rem),linear-gradient(125deg,#10191c,#10282f);box-shadow:0 22px 48px rgba(18,51,61,.13);color:white}.twin-pipeline:after{position:absolute;right:-3rem;top:-5rem;width:14rem;height:14rem;border:1px solid rgba(112,213,236,.1);border-radius:50%;content:''}.twin-pipeline>header{position:relative;z-index:1;display:flex;align-items:end;justify-content:space-between;gap:var(--cp-space-5)}.twin-pipeline h3{margin:var(--cp-space-2) 0 0;font-size:var(--cp-text-xl)}.twin-pipeline header p{max-width:48rem;margin:0;color:#9fb1b5;font-size:var(--cp-text-sm)}.twin-pipeline ol{position:relative;z-index:1;display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:1px;margin:0;padding:1px;border:1px solid rgba(112,213,236,.13);border-radius:var(--cp-radius-md);background:rgba(112,213,236,.13);list-style:none}.twin-pipeline li{position:relative;display:grid;min-height:8.5rem;align-content:center;gap:.45rem;padding:var(--cp-space-4);background:rgba(7,17,20,.82)}.twin-pipeline li:not(:last-child):after{position:absolute;right:-.48rem;top:50%;z-index:2;width:.8rem;height:.8rem;border-top:1px solid #70d5ec;border-right:1px solid #70d5ec;background:#102126;content:'';transform:translateY(-50%) rotate(45deg)}.twin-pipeline strong{color:#edfafd;font:800 clamp(1.25rem,2vw,2rem)/1 var(--cp-font-mono)}.twin-pipeline li span{color:#d2dfe2;font-size:var(--cp-text-sm);font-weight:700}.twin-pipeline small{color:#6fbfd1;font:750 .63rem/1 var(--cp-font-mono);letter-spacing:.08em}.twin-pipeline .pipeline-result{background:linear-gradient(145deg,rgba(25,113,136,.78),rgba(10,40,48,.92))}.twin-pipeline .pipeline-result strong{color:#fff;text-shadow:0 0 22px rgba(112,213,236,.32)}
.loop-panel{position:relative;overflow:hidden;border-color:rgba(112,213,236,.2);background:radial-gradient(circle at 82% 10%,rgba(29,181,215,.16),transparent 20rem),linear-gradient(130deg,#101719,#11252b);box-shadow:0 24px 56px rgba(18,51,61,.16);color:#f7fbfc}.loop-panel:after{position:absolute;right:-5rem;bottom:-8rem;width:20rem;height:20rem;border:1px solid rgba(112,213,236,.1);border-radius:50%;content:''}.loop-copy,.loop-diagram,.loop-return{position:relative;z-index:1}.loop-copy p{color:#aebec2}.loop-diagram>div{border-color:rgba(112,213,236,.16);background:rgba(255,255,255,.055);box-shadow:inset 0 1px rgba(255,255,255,.05)}.loop-diagram .loop-core{border-color:#65d3ea;background:rgba(79,196,220,.13);box-shadow:0 0 28px rgba(79,196,220,.12)}.loop-diagram strong{color:#f5fcfd}.loop-diagram span{color:#a9b9bd}.loop-diagram>i{color:#70d5ec;filter:drop-shadow(0 0 5px rgba(112,213,236,.55))}.loop-return{color:#8fdced}
.metric-grid article{position:relative;overflow:hidden;border:1px solid rgba(11,107,136,.13);border-top:0;border-radius:var(--cp-radius-md);background:linear-gradient(155deg,#fff,#f2fafc);box-shadow:0 14px 30px rgba(31,70,82,.07)}.metric-grid article:before{position:absolute;inset:0 0 auto;height:3px;background:linear-gradient(90deg,var(--cp-tech),#74d9ed);content:''}.metric-grid article:after{position:absolute;right:-2.2rem;top:-2.2rem;width:6rem;height:6rem;border:1px solid rgba(13,145,181,.09);border-radius:50%;content:''}
.validation-map{border-color:rgba(112,213,236,.19);background:radial-gradient(circle at 8% 100%,rgba(176,18,55,.13),transparent 23rem),linear-gradient(135deg,#111719,#10262d);box-shadow:0 24px 55px rgba(18,51,61,.15)}.validation-map li{background:rgba(8,18,22,.78)}.validation-map li:hover{background:rgba(34,75,86,.52)}
.ablation-panel{border-color:rgba(11,107,136,.14);background:linear-gradient(105deg,#fff,#f4fbfc);box-shadow:0 15px 34px rgba(31,70,82,.06)}.ablation-panel dt{text-shadow:0 8px 22px rgba(176,18,55,.12)}
.timeline{position:relative;border-color:rgba(11,107,136,.18);background:linear-gradient(120deg,#f7fcfd,#fff);box-shadow:0 14px 32px rgba(31,70,82,.06)}.timeline>i{height:2px;background:linear-gradient(90deg,rgba(11,107,136,.2),var(--cp-tech),rgba(11,107,136,.2))}.timeline>b{box-shadow:0 8px 18px rgba(176,18,55,.2);letter-spacing:.07em}.timeline em{border-color:rgba(11,107,136,.16);background:white}.timeline em:last-child{box-shadow:inset 0 0 20px rgba(176,18,55,.045)}
.case-grid article{position:relative;overflow:hidden;border-color:rgba(11,107,136,.14);background:linear-gradient(150deg,#fff,#f7fbfc);box-shadow:0 16px 36px rgba(31,70,82,.07)}.case-grid article:before{position:absolute;left:0;top:0;width:4px;height:100%;background:linear-gradient(var(--cp-tech),transparent);content:''}.case-grid article:last-child:before{background:linear-gradient(var(--cp-action-primary),transparent)}
.governance-chart{display:grid;gap:var(--cp-space-5);padding:var(--cp-space-5);border:1px solid rgba(11,107,136,.16);border-radius:var(--cp-radius-lg);background:linear-gradient(145deg,#f8fcfd,#fff);box-shadow:0 18px 42px rgba(31,70,82,.075)}.governance-chart>header{display:grid;grid-template-columns:minmax(12rem,.42fr) minmax(20rem,1fr) auto;align-items:end;gap:var(--cp-space-4);padding-bottom:var(--cp-space-4);border-bottom:1px solid rgba(11,107,136,.13)}.governance-chart h3{margin:0 0 var(--cp-space-1);font-size:var(--cp-text-xl)}.governance-chart header p{margin:0;color:var(--cp-text-secondary);font-size:var(--cp-text-sm);line-height:1.55}.chart-legend{display:flex;gap:var(--cp-space-3);color:var(--cp-text-muted);font:700 var(--cp-text-xs)/1 var(--cp-font-mono)}.chart-legend span{display:flex;align-items:center;gap:.4rem}.chart-legend i{width:.8rem;height:.35rem;border-radius:3px}.chart-legend .natural{background:#9bacb0}.chart-legend .intervention{background:linear-gradient(90deg,var(--cp-tech),#55cfe8)}.chart-cases{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:var(--cp-space-5)}.chart-cases article{display:grid;gap:var(--cp-space-4);padding:var(--cp-space-4);border:1px solid rgba(11,107,136,.12);border-radius:var(--cp-radius-md);background:rgba(255,255,255,.82)}.chart-case-title{display:flex;align-items:center;justify-content:space-between}.chart-case-title span{color:var(--cp-tech);font:800 var(--cp-text-xs)/1 var(--cp-font-mono);letter-spacing:.08em}.chart-case-title strong{font-size:var(--cp-text-md)}.bar-row{display:grid;grid-template-columns:6.5rem 1fr;align-items:center;gap:var(--cp-space-3)}.bar-row>span{color:var(--cp-text-secondary);font-size:var(--cp-text-xs);font-weight:700}.bar-row>div{display:grid;gap:.35rem}.bar-row i{display:flex;width:var(--bar);min-width:2.75rem;height:1.05rem;align-items:center;justify-content:flex-end;border-radius:3px;font-style:normal}.bar-row i.natural{background:linear-gradient(90deg,#d7e0e2,#9bacb0)}.bar-row i.intervention{background:linear-gradient(90deg,#087792,#4bc7e1);box-shadow:0 4px 12px rgba(13,145,181,.16)}.bar-row b{padding:0 .35rem;color:#102126;font:800 .68rem/1 var(--cp-font-mono)}.bar-row i.intervention b{color:white}.governance-chart footer{display:flex;align-items:center;gap:var(--cp-space-3);padding:var(--cp-space-3) var(--cp-space-4);border-left:3px solid var(--cp-action-primary);background:var(--cp-surface-selected);font-size:var(--cp-text-sm)}.governance-chart footer strong{color:var(--cp-action-primary);white-space:nowrap}.governance-chart footer span{color:var(--cp-text-secondary)}
.chart-note{color:var(--cp-text-muted);font-size:.68rem;text-align:right}
.case-grid article:last-child:before{background:linear-gradient(#1aa8c7,transparent)}
.governance-chart>header{grid-template-columns:minmax(12rem,.42fr) minmax(20rem,1fr)}
.governance-chart footer{border-left-color:#149fbd;background:#eaf8fb}.governance-chart footer strong{color:#087b99}
.timeline>b{background:linear-gradient(90deg,#087b99,#20b6d2)}.timeline em:last-child{border-color:#9fddea;background:#edfafd;color:#087b99}
.research-finding{border-left-color:#20b6d2;background:radial-gradient(circle at 86% 10%,rgba(49,202,228,.18),transparent 18rem),linear-gradient(115deg,#071d2c,#0a2637 58%,#09202e);box-shadow:0 24px 52px rgba(7,41,57,.2)}.research-finding span{color:#78e1f2}.research-finding small{color:#b8ced7}
.trajectory-layout{display:grid;grid-template-columns:minmax(30rem,1.35fr) minmax(23rem,.65fr);gap:var(--cp-space-5)}
.trajectory-plot{position:relative;min-height:25rem;overflow:hidden;border:1px solid rgba(21,166,199,.18);border-radius:var(--cp-radius-md);background:radial-gradient(circle at 76% 24%,rgba(54,205,230,.13),transparent 18rem),linear-gradient(145deg,#f9fdfe,#eef9fc)}.trajectory-plot:after{position:absolute;top:0;bottom:0;width:22%;background:linear-gradient(90deg,transparent,rgba(255,255,255,.66),transparent);content:'';animation:signal-scan 6s ease-in-out infinite;pointer-events:none}.trajectory-plot svg{position:absolute;inset:0;width:100%;height:100%}.trajectory-grid{fill:none;stroke:rgba(17,134,163,.1);stroke-width:1}.trajectory-base{fill:none;stroke:#87a8b1;stroke-dasharray:4 7;stroke-width:2}.origin-node{fill:#fff;stroke:#168ca8;stroke-width:4}.trajectory-ghost{fill:none;stroke:rgba(22,127,153,.12);stroke-width:10}.trajectory-branch{fill:none;stroke-linecap:round;stroke-width:4;stroke-dasharray:12 9;animation:signal-flow 2.2s linear infinite}.branch--conflict{stroke:url(#trajectoryUp)}.branch--resource{stroke:url(#trajectoryDown);animation-duration:2.8s}.endpoint{fill:#fff;stroke-width:5}.endpoint--conflict{stroke:#0ca3c2}.endpoint--resource{stroke:#315a7c}.endpoint-halo{fill:none;stroke-width:2;transform-box:fill-box;transform-origin:center;animation:node-pulse 2.8s ease-out infinite}.halo--conflict{stroke:rgba(28,191,218,.42)}.halo--resource{stroke:rgba(49,90,124,.38);animation-delay:.7s}
.plot-axis,.plot-origin,.plot-result{position:absolute;z-index:2}.plot-axis{right:1rem;color:var(--cp-text-muted);font:800 .64rem/1 var(--cp-font-mono);letter-spacing:.08em}.plot-axis--positive{top:1rem}.plot-axis--negative{bottom:1rem}.plot-origin{left:20%;top:52%;padding:.35rem .55rem;transform:translate(-50%,-50%);border:1px solid rgba(17,134,163,.2);border-radius:99px;background:rgba(255,255,255,.88);color:#17647a;font:800 .66rem/1 var(--cp-font-mono);white-space:nowrap}.plot-result{display:flex;align-items:baseline;gap:.55rem;padding:.5rem .65rem;border:1px solid rgba(18,139,166,.18);border-radius:var(--cp-radius-sm);background:rgba(255,255,255,.9);box-shadow:0 8px 20px rgba(13,91,111,.09);backdrop-filter:blur(5px)}.plot-result b{color:var(--cp-tech);font:800 .65rem/1 var(--cp-font-mono);letter-spacing:.08em}.plot-result strong{color:#123a49;font:800 1rem/1 var(--cp-font-mono)}.plot-result--conflict{right:4%;top:8%}.plot-result--resource{right:10%;bottom:8%}
.trajectory-cards{display:grid;grid-template-rows:1fr 1fr;gap:var(--cp-space-3)}.trajectory-card{display:grid;align-content:center;gap:var(--cp-space-4);padding:var(--cp-space-4);border:1px solid rgba(12,125,153,.15);border-radius:var(--cp-radius-md);background:rgba(255,255,255,.9);box-shadow:0 12px 28px rgba(25,72,86,.07);transition:transform .25s ease,border-color .25s ease,box-shadow .25s ease}.trajectory-card:hover{transform:translateX(-.3rem);border-color:rgba(21,173,203,.42);box-shadow:0 18px 34px rgba(15,109,135,.14)}.trajectory-card header{display:grid;grid-template-columns:auto 1fr auto;align-items:center;gap:.65rem}.trajectory-card header span{color:var(--cp-tech);font:800 .68rem/1 var(--cp-font-mono);letter-spacing:.07em}.trajectory-card header strong{font-size:var(--cp-text-md)}.trajectory-card header em{padding:.28rem .5rem;border-radius:99px;background:#e6f8fb;color:#087b99;font:800 .65rem/1 var(--cp-font-mono);font-style:normal;white-space:nowrap}.trajectory-card--resource header em{background:#edf2f7;color:#315a7c}.trajectory-card dl{display:grid;grid-template-columns:repeat(3,1fr);margin:0;border-top:1px solid rgba(13,120,147,.12);border-bottom:1px solid rgba(13,120,147,.12)}.trajectory-card dl div{display:grid;gap:.35rem;padding:.8rem .5rem;text-align:center}.trajectory-card dl div+div{border-left:1px solid rgba(13,120,147,.12)}.trajectory-card dt{color:#0b708c;font:800 .92rem/1 var(--cp-font-mono)}.trajectory-card dd{margin:0;color:var(--cp-text-muted);font-size:.68rem}.trajectory-card p{margin:0;color:var(--cp-text-secondary);font-size:var(--cp-text-xs);line-height:1.55}
.governance-chart:has(.trajectory-card--conflict:hover) .branch--conflict,.governance-chart:has(.trajectory-card--resource:hover) .branch--resource{stroke-width:7;filter:drop-shadow(0 0 5px rgba(20,185,214,.46))}
@keyframes signal-flow{to{stroke-dashoffset:-42}}@keyframes node-pulse{0%{opacity:.8;transform:scale(.75)}70%,100%{opacity:0;transform:scale(1.65)}}@keyframes signal-scan{0%,18%{left:-28%;opacity:0}35%{opacity:.65}60%,100%{left:108%;opacity:0}}
@media(prefers-reduced-motion:reduce){.trajectory-plot:after,.trajectory-branch,.endpoint-halo{animation:none}.trajectory-card{transition:none}}
.case-link{display:inline-flex;align-items:center;gap:.5rem;padding:.7rem 1rem;border:1px solid rgba(11,107,136,.17);border-radius:999px;background:#fff;box-shadow:0 8px 20px rgba(31,70,82,.06);transition:gap var(--cp-motion-standard) ease,box-shadow var(--cp-motion-standard) ease}.case-link:hover{gap:.8rem;box-shadow:0 12px 26px rgba(31,70,82,.11)}
.boundary-panel{position:relative;display:grid;gap:var(--cp-space-5);overflow:hidden;padding:var(--cp-space-6);border:1px solid rgba(201,168,84,.42);border-radius:var(--cp-radius-lg);background:linear-gradient(130deg,#fffaf0,#f8f2e3);box-shadow:0 18px 40px rgba(102,79,31,.07)}.boundary-panel:after{position:absolute;right:-4rem;top:-6rem;width:16rem;height:16rem;border:1px solid rgba(170,133,46,.09);border-radius:50%;box-shadow:0 0 0 2.4rem rgba(170,133,46,.025);content:'';pointer-events:none}.boundary-panel>*{position:relative;z-index:1}.boundary-panel ul{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:var(--cp-space-3) var(--cp-space-6);margin:0;padding-left:1.2rem;color:var(--cp-evidence-text);font-size:var(--cp-text-sm);line-height:1.7}.boundary-panel>div{display:flex;flex-wrap:wrap;gap:var(--cp-space-2)}.boundary-panel a{display:inline-flex;min-height:var(--cp-control-height);align-items:center;padding:0 var(--cp-space-3);border:1px solid #bba767;border-radius:var(--cp-radius-sm);background:white;color:var(--cp-evidence-text);font-size:var(--cp-text-sm);font-weight:700;text-decoration:none;box-shadow:0 6px 15px rgba(102,79,31,.055)}
@media(max-width:1100px){.research-focus{grid-template-columns:1fr}.research-focus>header{display:flex;align-items:end;justify-content:space-between;border-right:0;border-bottom:1px solid var(--cp-tech-line);padding:0 0 var(--cp-space-4)}.focus-marker{font-size:1.5rem}.innovation-hero{grid-template-columns:1fr}.hero-proof{grid-template-columns:repeat(3,1fr)}.hero-proof div{grid-template-columns:1fr}.twin-pipeline>header{align-items:start;flex-direction:column}.twin-pipeline ol{grid-template-columns:repeat(3,1fr)}.loop-panel{grid-template-columns:1fr}.loop-return{grid-column:1}.metric-grid{grid-template-columns:repeat(2,1fr)}.validation-map{grid-template-columns:1fr}.ablation-panel{grid-template-columns:1fr}.governance-chart>header{grid-template-columns:1fr auto}.governance-chart>header>.eyebrow{grid-column:1/-1}.trajectory-layout{grid-template-columns:1fr}.trajectory-cards{grid-template-columns:repeat(2,minmax(0,1fr));grid-template-rows:auto}}
@media(max-width:767px){.innovation-page{gap:var(--cp-space-5);padding:var(--cp-space-4)}.innovation-hero{min-height:0;padding:var(--cp-space-5)}.innovation-hero h1{font-size:2.25rem}.hero-proof{grid-template-columns:1fr}.hero-proof div{grid-template-columns:6rem 1fr}.research-focus{padding:var(--cp-space-4)}.research-focus>header{align-items:flex-start;flex-direction:column}.focus-grid{grid-template-columns:1fr}.chapter-heading{align-items:flex-start;flex-direction:column}.chapter-heading>div{align-items:flex-start}.chapter-number{min-width:3rem;font-size:2.25rem}.chapter-heading p{text-align:left}.twin-pipeline{padding:var(--cp-space-4)}.twin-pipeline ol{grid-template-columns:1fr}.twin-pipeline li{min-height:6.5rem}.twin-pipeline li:not(:last-child):after{right:50%;top:auto;bottom:-.45rem;transform:translateX(50%) rotate(135deg)}.innovation-grid,.case-grid,.chart-cases,.boundary-panel ul{grid-template-columns:1fr}.innovation-card{min-height:0;padding:var(--cp-space-5)}.card-index{font-size:2.65rem}.loop-panel{padding:var(--cp-space-4)}.loop-diagram{grid-template-columns:1fr}.loop-diagram>i{transform:rotate(90deg)}.metric-grid{grid-template-columns:1fr 1fr}.validation-map{padding:var(--cp-space-4)}.validation-map li{grid-template-columns:2.3rem 1fr}.validation-map li b{grid-column:2;text-align:left}.ablation-panel dl{grid-template-columns:repeat(2,1fr)}.ablation-panel dl div{border-top:1px solid var(--cp-border-default)}.timeline{grid-template-columns:1fr}.timeline>i{width:1px;height:1.6rem;justify-self:center}.timeline>div{grid-template-columns:1fr}.case-grid dl{grid-template-columns:1fr}.case-grid dl div{border-top:1px solid var(--cp-border-default);border-left:0}.case-grid dl div:first-child{border-top:0}.governance-chart>header{grid-template-columns:1fr}.chart-legend{justify-self:start}.case-link{justify-self:start}.boundary-panel{padding:var(--cp-space-4)}}
@media(max-width:767px){.trajectory-cards{grid-template-columns:1fr}.trajectory-plot{min-height:21rem}.plot-result{padding:.4rem}.plot-result--conflict{right:2%}.plot-result--resource{right:4%}.trajectory-card header{grid-template-columns:auto 1fr}.trajectory-card header em{grid-column:1/-1;justify-self:start}}
@media(max-width:480px){.metric-grid{grid-template-columns:1fr}.ablation-panel dl{grid-template-columns:1fr}}
.innovation-card:after{display:none}.innovation-card .card-kicker{display:inline-flex;align-items:center;gap:.8rem;color:#087b99;font:850 .92rem/1 var(--cp-font-mono);letter-spacing:.1em}.innovation-card .card-kicker:before{width:.5rem;height:.5rem;border-radius:50%;background:#26bad5;box-shadow:0 0 0 .34rem rgba(38,186,213,.09);content:''}.innovation-card .card-kicker:after{width:3rem;height:1px;background:linear-gradient(90deg,rgba(38,186,213,.78),transparent);content:''}.innovation-card header{align-items:center;padding-bottom:var(--cp-space-4);border-bottom:1px solid rgba(11,107,136,.13)}.innovation-card header i{width:3rem;height:3rem;font-size:var(--cp-text-md);box-shadow:0 0 0 5px rgba(13,145,181,.035),0 9px 20px rgba(11,107,136,.09)}

/* System subsection treatment: retain the roadshow content, remove the microsite chrome. */
.innovation-page{--cp-surface-canvas:#0b090a;--cp-surface-default:#151113;--cp-surface-subtle:#1c1719;--cp-surface-selected:#29171d;--cp-text-primary:#f1ece7;--cp-text-secondary:#b9b0aa;--cp-text-muted:#9e958f;--cp-border-default:#2a2428;--cp-border-subtle:#241f22;--cp-border-strong:#51464c;--cp-action-primary:#c51642;--cp-evidence:#d4af37;--cp-evidence-surface:#211d12;--cp-evidence-text:#e2c65f;--cp-tech:#9e958f;--cp-tech-line:#2a2428;gap:var(--cp-space-5);max-width:none;min-height:calc(100vh - 7.5rem);padding:var(--cp-space-4) var(--cp-content-gutter) var(--cp-space-8);background:#0b090a;color:#f1ece7}
.innovation-page:before,.innovation-hero:before,.innovation-hero:after,.research-focus:after,.focus-grid article:after,.innovation-card:before,.innovation-card:after,.twin-pipeline:after,.loop-panel:after,.metric-grid article:before,.metric-grid article:after,.case-grid article:before,.research-finding:after,.boundary-panel:after,.trajectory-plot:after,.hero-proof div:after,.innovation-card .card-kicker:before,.innovation-card .card-kicker:after{display:none}
.breadcrumb{padding:.4rem .65rem;border:1px solid #2a2428;border-radius:6px;background:#151113;color:#9e958f;backdrop-filter:none}
.innovation-hero{min-height:0;grid-template-columns:minmax(0,1.5fr) minmax(17rem,.5fr);gap:var(--cp-space-5);align-items:center;padding:var(--cp-space-5);border:1px solid #2a2428;border-radius:8px;background:#151113;box-shadow:none;color:#f1ece7}.innovation-hero .eyebrow:before{background:#c51642}.eyebrow{color:#c51642}.innovation-hero h1{max-width:52rem;margin:var(--cp-space-3) 0 0;font-size:clamp(2.2rem,3.6vw,3.6rem);line-height:1.05}.innovation-hero h1 em{background:none;color:#f1ece7}.innovation-hero p{margin:var(--cp-space-3) 0 0;color:#9e958f;font-size:var(--cp-text-sm);line-height:1.65}.hero-tags{margin-top:var(--cp-space-3)}.hero-tags span{padding:.35rem .55rem;border:1px solid #51464c;border-radius:4px;background:#1c1719;color:#9e958f;letter-spacing:.06em}.hero-proof{border:1px solid #2a2428;border-radius:6px;background:#2a2428;box-shadow:none;backdrop-filter:none}.hero-proof div{min-height:0;padding:var(--cp-space-3);background:#1c1719}.hero-proof strong{color:#f1ece7;text-shadow:none}.hero-proof span{color:#9e958f}
.research-focus,.loop-panel,.validation-map,.ablation-panel,.timeline,.governance-chart,.twin-pipeline,.research-finding,.boundary-panel{border:1px solid #2a2428;border-radius:8px;background:#151113;box-shadow:none;color:#f1ece7}.research-focus{grid-template-columns:10rem minmax(0,1fr);padding:var(--cp-space-4)}.focus-marker{color:#51464c;font-size:1.4rem}.focus-grid article,.innovation-card,.loop-diagram>div,.metric-grid article,.validation-map li,.case-grid article,.chart-cases article,.trajectory-card,.trajectory-plot,.timeline em{border:1px solid #2a2428;border-radius:6px;background:#1c1719;box-shadow:none;color:#f1ece7}.focus-grid article{padding:var(--cp-space-3)}.focus-grid article>span,.focus-grid article>small,.focus-grid p,.innovation-card header,.innovation-card .card-kicker,.case-grid article>span,.case-link,.trajectory-card header span,.trajectory-card dt{color:#9e958f}.focus-grid article>span{font-size:2rem}.focus-grid article:hover,.innovation-card:hover,.trajectory-card:hover{border-color:#51464c;box-shadow:none;transform:none}.chapter-heading{padding-left:0;border-bottom-color:#2a2428}.chapter-heading:before{display:none}.chapter-number{background:none;color:#9e958f;text-shadow:none}.innovation-grid{gap:var(--cp-space-2)}.innovation-card{min-height:0;padding:var(--cp-space-4);transition:border-color var(--cp-motion-standard) ease}.innovation-card header i{width:2.5rem;height:2.5rem;border:1px solid #2a2428;border-radius:6px;background:#151113;box-shadow:none}.innovation-card p,.case-grid p,.loop-copy p,.twin-pipeline header p,.trajectory-card p{color:#b9b0aa;line-height:1.6}.innovation-card li{padding:.35rem .55rem;border:1px solid #2a2428;border-radius:4px;background:#151113;color:#9e958f}
.twin-pipeline,.loop-panel,.validation-map,.ablation-panel,.governance-chart{padding:var(--cp-space-4)}.twin-pipeline ol,.validation-map ol{border-color:#2a2428;border-radius:6px;background:#2a2428}.twin-pipeline li{min-height:6.5rem;background:#1c1719}.twin-pipeline li:not(:last-child):after{border-color:#51464c;background:#1c1719}.twin-pipeline strong,.twin-pipeline li span,.loop-diagram strong{color:#f1ece7}.twin-pipeline small,.loop-diagram small,.loop-diagram>i,.loop-return{color:#9e958f;filter:none}.twin-pipeline .pipeline-result,.loop-diagram .loop-core{border-color:#c51642;background:#29171d;box-shadow:none}.twin-pipeline .pipeline-result strong{color:#f1ece7;text-shadow:none}.metric-grid{gap:0;border:1px solid #2a2428;background:#151113}.metric-grid article{padding:var(--cp-space-3);border:0;border-right:1px solid #2a2428;border-radius:0;background:#151113}.metric-grid article:last-child{border-right:0}.metric-grid strong{color:#f1ece7;font-size:1.8rem}.validation-map li{border:0;border-radius:0}.validation-map li:hover{background:#1c1719}.validation-map li>span,.validation-map li b{color:#9e958f}.validation-map li small{color:#9e958f}.ablation-panel dt{color:#c51642;text-shadow:none}.timeline>i{height:1px;background:#51464c}.timeline>b{border-radius:4px;background:#c51642;box-shadow:none}.timeline em:last-child{border-color:#c51642;background:#29171d;color:#f1ece7;box-shadow:none}
.case-grid{gap:var(--cp-space-2)}.case-grid article{padding:var(--cp-space-4)}.case-link{padding:.55rem .75rem;border:1px solid #51464c;border-radius:6px;background:#151113;box-shadow:none;transition:none}.case-link:hover{gap:.5rem;box-shadow:none}.research-finding{padding:var(--cp-space-4);border-left:3px solid #c51642}.research-finding span{color:#c51642}.research-finding p{font-size:clamp(1.2rem,2vw,1.75rem)}.research-finding small{color:#9e958f}.boundary-panel{border-color:#6d5a24;background:#211d12}.boundary-panel a{border-color:#6d5a24;border-radius:6px;background:#151113;color:#e2c65f;box-shadow:none}
.governance-chart>header{border-bottom-color:#2a2428}.chart-legend .natural,.bar-row i.natural{background:#2b6cb0}.chart-legend .intervention,.bar-row i.intervention{background:#319795;box-shadow:none}.governance-chart footer{border-left-color:#319795;background:#14201f}.governance-chart footer strong{color:#319795}.governance-chart footer span{color:#b9b0aa}.trajectory-plot{min-height:22rem;background:#100e0f}.trajectory-grid{stroke:#2a2428}.trajectory-base{stroke:#9e958f}.origin-node,.endpoint{fill:#151113}.branch--conflict,.endpoint--conflict{stroke:#2b6cb0}.branch--resource,.endpoint--resource{stroke:#319795}.endpoint-halo{display:none}.trajectory-branch{animation:none}.plot-origin,.plot-result{border:1px solid #51464c;border-radius:4px;background:#151113;color:#f1ece7;box-shadow:none;backdrop-filter:none}.plot-result b,.plot-result strong{color:#f1ece7}.trajectory-card{transition:border-color var(--cp-motion-standard) ease}.trajectory-card header em{border-radius:4px;background:#151113;color:#9e958f}.trajectory-card--resource header em{background:#151113;color:#9e958f}.trajectory-card dl{border-color:#2a2428}.trajectory-card dl div+div{border-color:#2a2428}.governance-chart:has(.trajectory-card--conflict:hover) .branch--conflict,.governance-chart:has(.trajectory-card--resource:hover) .branch--resource{stroke-width:4;filter:none}
</style>
